// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38-Gz5SfGG7MupzZlJX5v6eACPl8FCg8',
    appId: '1:6217043405:web:2d401836b0a2853b8f0884',
    messagingSenderId: '6217043405',
    projectId: 'mytestapp-8750d',
    authDomain: 'mytestapp-8750d.firebaseapp.com',
    storageBucket: 'mytestapp-8750d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIB9H3-b4XzkENgj-PlSMHHltYXPWAxns',
    appId: '1:6217043405:android:a000fec0be13734f8f0884',
    messagingSenderId: '6217043405',
    projectId: 'mytestapp-8750d',
    storageBucket: 'mytestapp-8750d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA70GZlL_JL0IgUAI-ZHRB6mBi6r2N3Cys',
    appId: '1:6217043405:ios:86565c321e9a6dc98f0884',
    messagingSenderId: '6217043405',
    projectId: 'mytestapp-8750d',
    storageBucket: 'mytestapp-8750d.appspot.com',
    iosBundleId: 'com.example.testingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA70GZlL_JL0IgUAI-ZHRB6mBi6r2N3Cys',
    appId: '1:6217043405:ios:3ec18919c411dda18f0884',
    messagingSenderId: '6217043405',
    projectId: 'mytestapp-8750d',
    storageBucket: 'mytestapp-8750d.appspot.com',
    iosBundleId: 'com.example.testingApp.RunnerTests',
  );
}
